version: '3'

services:
  postgres-users:
    image: postgres:9.6-alpine
    volumes:
      - users-volume:/var/lib/postgresql/data
    container_name: "postgres-users"
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: usersdb

  pgadmin4:
    image: dpage/pgadmin4:5.5
    volumes:
      - pgadmin-users-volume:/var/lib/pgadmin
    container_name: "pgadmin4-users"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pass123
    ports:
      - 8082:80

volumes:
  users-volume:
  pgadmin-users-volume:

networks:
  default:
    external:
      name: microservice-back-java